version = 0.1

[default.global.parameters]
stack_name = "employee-dashboard"
region = "ap-southeast-2"

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
confirm_changeset = true
